FROM python:3.11-slim

WORKDIR /app

COPY requirements-flask.txt .

RUN pip install --no-cache-dir -r requirements-flask.txt 

COPY flask_app.py .
COPY model.joblib .

EXPOSE 8000

CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:8000", "flask_app:app"]